services:
  postgres:
    image: postgres
    container_name: flyaway_postgres_db
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  mongo:
    image: mongo
    container_name: flyaway_mongo_db
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user

  mongo-express:
    image: mongo-express
    container_name: flyaway_mongo_express
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=user
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1026:1025
      - 8026:8025


volumes:
  postgres_data: {}
  mongo_data: {}