services:
  postgres:
    image: postgres
    container_name: flyaway_postgres_db
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  mongo:
    image: mongo
    container_name: flyaway_mongo_db
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
      - MONGO_INITDB_DATABASE=flyaway

  mongo-express:
    image: mongo-express
    container_name: flyaway_mongo_express
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=user
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1026:1025
      - 8026:8025

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: listen --forward-to http://host.docker.internal:8080/api/v1/payment/webhook
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    network_mode: host
    volumes:
      - ~/.config/stripe:/root/.config/stripe

volumes:
  postgres_data: {}
  mongo_data: {}