INSERT INTO countries (name, enabled) VALUES ('Afghanistan', false);
INSERT INTO countries (name, enabled) VALUES ('Albania', false);
INSERT INTO countries (name, enabled) VALUES ('Algeria', false);
INSERT INTO countries (name, enabled) VALUES ('American Samoa', false);
INSERT INTO countries (name, enabled) VALUES ('Andorra', false);
INSERT INTO countries (name, enabled) VALUES ('Angola', false);
INSERT INTO countries (name, enabled) VALUES ('Anguilla', false);
INSERT INTO countries (name, enabled) VALUES ('Antarctica', false);
INSERT INTO countries (name, enabled) VALUES ('Antigua and Barbuda', false);
INSERT INTO countries (name, enabled) VALUES ('Argentina', false);
INSERT INTO countries (name, enabled) VALUES ('Armenia', false);
INSERT INTO countries (name, enabled) VALUES ('Aruba', false);
INSERT INTO countries (name, enabled) VALUES ('Australia', false);
INSERT INTO countries (name, enabled) VALUES ('Austria', false);
INSERT INTO countries (name, enabled) VALUES ('Azerbaijan', false);
INSERT INTO countries (name, enabled) VALUES ('Bahamas', false);
INSERT INTO countries (name, enabled) VALUES ('Bahrain', false);
INSERT INTO countries (name, enabled) VALUES ('Bangladesh', false);
INSERT INTO countries (name, enabled) VALUES ('Barbados', false);
INSERT INTO countries (name, enabled) VALUES ('Belarus', false);
INSERT INTO countries (name, enabled) VALUES ('Belgium', false);
INSERT INTO countries (name, enabled) VALUES ('Belize', false);
INSERT INTO countries (name, enabled) VALUES ('Benin', false);
INSERT INTO countries (name, enabled) VALUES ('Bermuda', false);
INSERT INTO countries (name, enabled) VALUES ('Bhutan', false);
INSERT INTO countries (name, enabled) VALUES ('Bosnia and Herzegovina', false);
INSERT INTO countries (name, enabled) VALUES ('Botswana', false);
INSERT INTO countries (name, enabled) VALUES ('Bouvet Island', false);
INSERT INTO countries (name, enabled) VALUES ('Brazil', false);
INSERT INTO countries (name, enabled) VALUES ('British Indian Ocean Territory', false);
INSERT INTO countries (name, enabled) VALUES ('Brunei Darussalam', false);
INSERT INTO countries (name, enabled) VALUES ('Bulgaria', false);
INSERT INTO countries (name, enabled) VALUES ('Burkina Faso', false);
INSERT INTO countries (name, enabled) VALUES ('Burundi', false);
INSERT INTO countries (name, enabled) VALUES ('Cambodia', false);
INSERT INTO countries (name, enabled) VALUES ('Cameroon', false);
INSERT INTO countries (name, enabled) VALUES ('Canada', false);
INSERT INTO countries (name, enabled) VALUES ('Cape Verde', false);
INSERT INTO countries (name, enabled) VALUES ('Cayman Islands', false);
INSERT INTO countries (name, enabled) VALUES ('Central African Republic', false);
INSERT INTO countries (name, enabled) VALUES ('Chad', false);
INSERT INTO countries (name, enabled) VALUES ('Chile', false);
INSERT INTO countries (name, enabled) VALUES ('China', false);
INSERT INTO countries (name, enabled) VALUES ('Christmas Island', false);
INSERT INTO countries (name, enabled) VALUES ('Cocos (Keeling) Islands', false);
INSERT INTO countries (name, enabled) VALUES ('Colombia', false);
INSERT INTO countries (name, enabled) VALUES ('Comoros', false);
INSERT INTO countries (name, enabled) VALUES ('Congo', false);
INSERT INTO countries (name, enabled) VALUES ('Cook Islands', false);
INSERT INTO countries (name, enabled) VALUES ('Costa Rica', false);
INSERT INTO countries (name, enabled) VALUES ('Croatia', false);
INSERT INTO countries (name, enabled) VALUES ('Cuba', false);
INSERT INTO countries (name, enabled) VALUES ('Cyprus', false);
INSERT INTO countries (name, enabled) VALUES ('Czech Republic', false);
INSERT INTO countries (name, enabled) VALUES ('Denmark', false);
INSERT INTO countries (name, enabled) VALUES ('Djibouti', false);
INSERT INTO countries (name, enabled) VALUES ('Dominica', false);
INSERT INTO countries (name, enabled) VALUES ('Dominican Republic', false);
INSERT INTO countries (name, enabled) VALUES ('Ecuador', false);
INSERT INTO countries (name, enabled) VALUES ('Egypt', false);
INSERT INTO countries (name, enabled) VALUES ('El Salvador', false);
INSERT INTO countries (name, enabled) VALUES ('Equatorial Guinea', false);
INSERT INTO countries (name, enabled) VALUES ('Eritrea', false);
INSERT INTO countries (name, enabled) VALUES ('Estonia', false);
INSERT INTO countries (name, enabled) VALUES ('Ethiopia', false);
INSERT INTO countries (name, enabled) VALUES ('Falkland Islands (Malvinas)', false);
INSERT INTO countries (name, enabled) VALUES ('Faroe Islands', false);
INSERT INTO countries (name, enabled) VALUES ('Fiji', false);
INSERT INTO countries (name, enabled) VALUES ('Finland', false);
INSERT INTO countries (name, enabled) VALUES ('France', false);
INSERT INTO countries (name, enabled) VALUES ('French Guiana', false);
INSERT INTO countries (name, enabled) VALUES ('French Polynesia', false);
INSERT INTO countries (name, enabled) VALUES ('French Southern Territories', false);
INSERT INTO countries (name, enabled) VALUES ('Gabon', false);
INSERT INTO countries (name, enabled) VALUES ('Gambia', false);
INSERT INTO countries (name, enabled) VALUES ('Georgia', false);
INSERT INTO countries (name, enabled) VALUES ('Germany', false);
INSERT INTO countries (name, enabled) VALUES ('Ghana', false);
INSERT INTO countries (name, enabled) VALUES ('Gibraltar', false);
INSERT INTO countries (name, enabled) VALUES ('Greece', false);
INSERT INTO countries (name, enabled) VALUES ('Greenland', false);
INSERT INTO countries (name, enabled) VALUES ('Grenada', false);
INSERT INTO countries (name, enabled) VALUES ('Guadeloupe', false);
INSERT INTO countries (name, enabled) VALUES ('Guam', false);
INSERT INTO countries (name, enabled) VALUES ('Guatemala', false);
INSERT INTO countries (name, enabled) VALUES ('Guernsey', false);
INSERT INTO countries (name, enabled) VALUES ('Guinea', false);
INSERT INTO countries (name, enabled) VALUES ('Guinea-Bissau', false);
INSERT INTO countries (name, enabled) VALUES ('Guyana', false);
INSERT INTO countries (name, enabled) VALUES ('Haiti', false);
INSERT INTO countries (name, enabled) VALUES ('Heard Island and McDonald Islands', false);
INSERT INTO countries (name, enabled) VALUES ('Holy See (Vatican City State)', false);
INSERT INTO countries (name, enabled) VALUES ('Honduras', false);
INSERT INTO countries (name, enabled) VALUES ('Hong Kong', false);
INSERT INTO countries (name, enabled) VALUES ('Hungary', false);
INSERT INTO countries (name, enabled) VALUES ('Iceland', false);
INSERT INTO countries (name, enabled) VALUES ('India', false);
INSERT INTO countries (name, enabled) VALUES ('Indonesia', false);
INSERT INTO countries (name, enabled) VALUES ('Iran', false);
INSERT INTO countries (name, enabled) VALUES ('Iraq', false);
INSERT INTO countries (name, enabled) VALUES ('Ireland', false);
INSERT INTO countries (name, enabled) VALUES ('Isle of Man', false);
INSERT INTO countries (name, enabled) VALUES ('Israel', false);
INSERT INTO countries (name, enabled) VALUES ('Italy', false);
INSERT INTO countries (name, enabled) VALUES ('Jamaica', false);
INSERT INTO countries (name, enabled) VALUES ('Japan', false);
INSERT INTO countries (name, enabled) VALUES ('Jersey', false);
INSERT INTO countries (name, enabled) VALUES ('Jordan', false);
INSERT INTO countries (name, enabled) VALUES ('Kazakhstan', false);
INSERT INTO countries (name, enabled) VALUES ('Kenya', false);
INSERT INTO countries (name, enabled) VALUES ('Kiribati', false);
INSERT INTO countries (name, enabled) VALUES ('Kuwait', false);
INSERT INTO countries (name, enabled) VALUES ('Kyrgyzstan', false);
INSERT INTO countries (name, enabled) VALUES ('Lao Peoples Democratic Republic', false);
INSERT INTO countries (name, enabled) VALUES ('Latvia', false);
INSERT INTO countries (name, enabled) VALUES ('Lebanon', false);
INSERT INTO countries (name, enabled) VALUES ('Lesotho', false);
INSERT INTO countries (name, enabled) VALUES ('Liberia', false);
INSERT INTO countries (name, enabled) VALUES ('Libya', false);
INSERT INTO countries (name, enabled) VALUES ('Liechtenstein', false);
INSERT INTO countries (name, enabled) VALUES ('Lithuania', false);
INSERT INTO countries (name, enabled) VALUES ('Luxembourg', false);
INSERT INTO countries (name, enabled) VALUES ('Macao', false);
INSERT INTO countries (name, enabled) VALUES ('Madagascar', false);
INSERT INTO countries (name, enabled) VALUES ('Malawi', false);
INSERT INTO countries (name, enabled) VALUES ('Malaysia', false);
INSERT INTO countries (name, enabled) VALUES ('Maldives', false);
INSERT INTO countries (name, enabled) VALUES ('Mali', false);
INSERT INTO countries (name, enabled) VALUES ('Malta', false);
INSERT INTO countries (name, enabled) VALUES ('Marshall Islands', false);
INSERT INTO countries (name, enabled) VALUES ('Martinique', false);
INSERT INTO countries (name, enabled) VALUES ('Mauritania', false);
INSERT INTO countries (name, enabled) VALUES ('Mauritius', false);
INSERT INTO countries (name, enabled) VALUES ('Mayotte', false);
INSERT INTO countries (name, enabled) VALUES ('Mexico', false);
INSERT INTO countries (name, enabled) VALUES ('Monaco', false);
INSERT INTO countries (name, enabled) VALUES ('Mongolia', false);
INSERT INTO countries (name, enabled) VALUES ('Montenegro', false);
INSERT INTO countries (name, enabled) VALUES ('Montserrat', false);
INSERT INTO countries (name, enabled) VALUES ('Morocco', false);
INSERT INTO countries (name, enabled) VALUES ('Mozambique', false);
INSERT INTO countries (name, enabled) VALUES ('Myanmar', false);
INSERT INTO countries (name, enabled) VALUES ('Namibia', false);
INSERT INTO countries (name, enabled) VALUES ('Nauru', false);
INSERT INTO countries (name, enabled) VALUES ('Nepal', false);
INSERT INTO countries (name, enabled) VALUES ('Netherlands', false);
INSERT INTO countries (name, enabled) VALUES ('New Caledonia', false);
INSERT INTO countries (name, enabled) VALUES ('New Zealand', false);
INSERT INTO countries (name, enabled) VALUES ('Nicaragua', false);
INSERT INTO countries (name, enabled) VALUES ('Niger', false);
INSERT INTO countries (name, enabled) VALUES ('Nigeria', false);
INSERT INTO countries (name, enabled) VALUES ('Niue', false);
INSERT INTO countries (name, enabled) VALUES ('Norfolk Island', false);
INSERT INTO countries (name, enabled) VALUES ('Northern Mariana Islands', false);
INSERT INTO countries (name, enabled) VALUES ('Norway', false);
INSERT INTO countries (name, enabled) VALUES ('Oman', false);
INSERT INTO countries (name, enabled) VALUES ('Pakistan', false);
INSERT INTO countries (name, enabled) VALUES ('Palau', false);
INSERT INTO countries (name, enabled) VALUES ('Panama', false);
INSERT INTO countries (name, enabled) VALUES ('Papua New Guinea', false);
INSERT INTO countries (name, enabled) VALUES ('Paraguay', false);
INSERT INTO countries (name, enabled) VALUES ('Peru', false);
INSERT INTO countries (name, enabled) VALUES ('Philippines', false);
INSERT INTO countries (name, enabled) VALUES ('Pitcairn', false);
INSERT INTO countries (name, enabled) VALUES ('Poland', false);
INSERT INTO countries (name, enabled) VALUES ('Portugal', false);
INSERT INTO countries (name, enabled) VALUES ('Puerto Rico', false);
INSERT INTO countries (name, enabled) VALUES ('Qatar', false);
INSERT INTO countries (name, enabled) VALUES ('Romania', false);
INSERT INTO countries (name, enabled) VALUES ('Russian Federation', false);
INSERT INTO countries (name, enabled) VALUES ('Rwanda', false);
INSERT INTO countries (name, enabled) VALUES ('Saint Kitts and Nevis', false);
INSERT INTO countries (name, enabled) VALUES ('Saint Lucia', false);
INSERT INTO countries (name, enabled) VALUES ('Saint Martin (French part)', false);
INSERT INTO countries (name, enabled) VALUES ('Saint Pierre and Miquelon', false);
INSERT INTO countries (name, enabled) VALUES ('Saint Vincent and the Grenadines', false);
INSERT INTO countries (name, enabled) VALUES ('Samoa', false);
INSERT INTO countries (name, enabled) VALUES ('San Marino', false);
INSERT INTO countries (name, enabled) VALUES ('Sao Tome and Principe', false);
INSERT INTO countries (name, enabled) VALUES ('Saudi Arabia', false);
INSERT INTO countries (name, enabled) VALUES ('Senegal', false);
INSERT INTO countries (name, enabled) VALUES ('Serbia', false);
INSERT INTO countries (name, enabled) VALUES ('Seychelles', false);
INSERT INTO countries (name, enabled) VALUES ('Sierra Leone', false);
INSERT INTO countries (name, enabled) VALUES ('Singapore', false);
INSERT INTO countries (name, enabled) VALUES ('Sint Maarten (Dutch part)', false);
INSERT INTO countries (name, enabled) VALUES ('Slovakia', false);
INSERT INTO countries (name, enabled) VALUES ('Slovenia', false);
INSERT INTO countries (name, enabled) VALUES ('Solomon Islands', false);
INSERT INTO countries (name, enabled) VALUES ('Somalia', false);
INSERT INTO countries (name, enabled) VALUES ('South Africa', false);
INSERT INTO countries (name, enabled) VALUES ('South Georgia and the South Sandwich Islands', false);
INSERT INTO countries (name, enabled) VALUES ('South Sudan', false);
INSERT INTO countries (name, enabled) VALUES ('Spain', false);
INSERT INTO countries (name, enabled) VALUES ('Sri Lanka', false);
INSERT INTO countries (name, enabled) VALUES ('Sudan', false);
INSERT INTO countries (name, enabled) VALUES ('Suriname', false);
INSERT INTO countries (name, enabled) VALUES ('Svalbard and Jan Mayen', false);
INSERT INTO countries (name, enabled) VALUES ('Swaziland', false);
INSERT INTO countries (name, enabled) VALUES ('Sweden', false);
INSERT INTO countries (name, enabled) VALUES ('Switzerland', false);
INSERT INTO countries (name, enabled) VALUES ('Syrian Arab Republic', false);
INSERT INTO countries (name, enabled) VALUES ('Taiwan', false);
INSERT INTO countries (name, enabled) VALUES ('Tajikistan', false);
INSERT INTO countries (name, enabled) VALUES ('Tanzania', false);
INSERT INTO countries (name, enabled) VALUES ('Thailand', false);
INSERT INTO countries (name, enabled) VALUES ('Timor-Leste', false);
INSERT INTO countries (name, enabled) VALUES ('Togo', false);
INSERT INTO countries (name, enabled) VALUES ('Tokelau', false);
INSERT INTO countries (name, enabled) VALUES ('Tonga', false);
INSERT INTO countries (name, enabled) VALUES ('Trinidad and Tobago', false);
INSERT INTO countries (name, enabled) VALUES ('Tunisia', false);
INSERT INTO countries (name, enabled) VALUES ('Turkey', false);
INSERT INTO countries (name, enabled) VALUES ('Turkmenistan', false);
INSERT INTO countries (name, enabled) VALUES ('Tuvalu', false);
INSERT INTO countries (name, enabled) VALUES ('Uganda', false);
INSERT INTO countries (name, enabled) VALUES ('Ukraine', false);
INSERT INTO countries (name, enabled) VALUES ('United Arab Emirates', false);
INSERT INTO countries (name, enabled) VALUES ('United Kingdom', false);
INSERT INTO countries (name, enabled) VALUES ('United States', false);
INSERT INTO countries (name, enabled) VALUES ('Uruguay', false);
INSERT INTO countries (name, enabled) VALUES ('Uzbekistan', false);
INSERT INTO countries (name, enabled) VALUES ('Vanuatu', false);
INSERT INTO countries (name, enabled) VALUES ('Venezuela', false);
INSERT INTO countries (name, enabled) VALUES ('Viet Nam', false);
INSERT INTO countries (name, enabled) VALUES ('Wallis and Futuna', false);
INSERT INTO countries (name, enabled) VALUES ('Western Sahara', false);
INSERT INTO countries (name, enabled) VALUES ('Yemen', false);
INSERT INTO countries (name, enabled) VALUES ('Zambia', false);
INSERT INTO countries (name, enabled) VALUES ('Zimbabwe', false);